export const SELECT_PRODUCT = 'SELECT_PRODUCT';
export const FETCH_DATA = 'FETCH_DATA';
export const RECEIVE_DATA = 'RECEIVE_DATA';
export const SET_SELECTED_PRODUCT = 'SET_SELECTED_PRODUCT';
export const UPDATE_IMAGE = 'UPDATE_IMAGE';
export const CLEAR_SELECTED_PRODUCT = 'CLEAR_SELECTED_PRODUCT';